server:
    port: 8080
spring:
    jpa:
        hibernate:
            ddl-auto: create
    thymeleaf:
        mode: LEGACYHTML5
        cache: false
    datasource:
        name: urms
        driver-class-name: org.postgresql.Driver
        url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:urms}
        username: ${DB_USER}
        password: ${DB_PASSWORD}
    mail:
        port: ${MAIL_PORT:587}
        username: ${MAIL_USER:urmsuite@gmail.com}
        password: ${MAIL_PASSWORD}
        host: ${MAIL_HOST:smtp.gmail.com}
        defaultEncoding: UTF-8
        properties:
            mail:
                smtp:
                    starttls:
                        enable: true
site:
    address: 81.2.254.48