server:
    port: 8080

spring:
    thymeleaf:
        mode: LEGACYHTML5
        cache: false
    mail:
        port: ${MAIL_PORT:587}
        username: ${MAIL_USER:urmsuite@gmail.com}
        password: ${MAIL_PASSWORD}
        host: ${MAIL_HOST:smtp.gmail.com}
        defaultEncoding: UTF-8
        properties:
            mail:
                smtp:
                    starttls:
                        enable: true