server:
    port: 8080
spring:
    thymeleaf:
        mode: LEGACYHTML5
        cache: false
    datasource:
        url: jdbc:postgresql://${DB_HOST:postgresql}:${DB_PORT:5432}/${DB_NAME:urms}
        username: ${DB_USER}
        password: ${DB_PASSWORD}
        testWhileIdle: True
        validationQuery: SELECT 1
        connectionProperties: useUnicode=true;characterEncoding=utf-8;
    mail:
        port: ${MAIL_PORT:465}
        username: ${MAIL_USER:urmsuite@yandex.com}
        password: ${MAIL_PASSWORD}
        host: ${MAIL_HOST:smtp.yandex.com}
        protocol: smtp
        defaultEncoding: UTF-8