server:
    port: 8080

spring:
    thymeleaf:
        mode: LEGACYHTML5
        cache: false
    mail:
        port: ${MAIL_PORT:587}
        username: ${MAIL_USER:urmsuite@gmail.com}
        password: ${MAIL_PASSWORD}
        host: ${MAIL_HOST:smtp.gmail.com}
        defaultEncoding: UTF-8
        properties:
            mail:
                smtp:
                    starttls:
                        enable: true
    datasource:
        url: jdbc:h2:~/urms
        username: sa
        password: sa
        driver-class-name: org.h2.Driver
    jpa:
        hibernate:
            ddl-auto: create
    h2:
        console:
            enabled: true
            path: /h2-console