server:
    port: 8080
email:
    username: ${MAIL_USER:urmsuite@yandex.com}
    password: ${MAIL_PASSWORD}
    from: ${MAIL_FROM:urmsuite@yandex.com}
    smtp:
        host: ${MAIL_HOST:smtp.yandex.com}
        port: ${MAIL_PORT:587}
        auth: true
        starttls:
             enable: true
spring:
    thymeleaf:
        mode: LEGACYHTML5
        cache: false
    datasource:
        url: jdbc:postgresql://${DB_HOST:postgresql}:${DB_PORT:5432}/${DB_NAME:urms}
        username: ${DB_USER}
        password: ${DB_PASSWORD}
        testWhileIdle: True
        validationQuery: SELECT 1
        connectionProperties: useUnicode=true;characterEncoding=utf-8;